language: php
php:
  - nightly
  - 7.1
  - 7.0
  - 5.6

before_script:
  - composer self-update
  - composer install --no-interaction

script: vendor/bin/phpunit --configuration phpunit.xml

notifications:
  email: false
