build: false
clone_depth: 1
clone_folder: c:\projects\m3uparser

init:
    - SET PATH=C:\tools\php71;%PATH%

install:
  - cinst php -y
  - cd c:\tools\php71
  - copy php.ini-production php.ini
  - echo date.timezone="UTC" >> php.ini

  - cd C:\projects\m3uparser

  - php -r "readfile('http://getcomposer.org/installer');" | php
  - php composer.phar self-update
  - php composer.phar install --prefer-source --no-interaction

test_script:
  - cd C:\projects\m3uparser
  - vendor\bin\phpunit.bat
